## Math 157: Intro to Mathematical Software
## UC San Diego, winter 2018

## Homework 3: due February 2, 2018

Please enter all answers within this notebook unless otherwise specified. As usual, don't forget to cite sources and collaborators.

Through this problem set, use the SageMath 8.1 kernel unless otherwise specified.

### Problem 1: Gradient vector fields

Grading criterion: correctness of code.

1a. Compute the gradient of $f(x,y) = 3\sin(x) - 2\cos(2y) - x - y$.

In [42]:
#source: http://doc.sagemath.org/html/en/reference/calculus/sage/calculus/calculus.html
f(x,y)=3*sin(x)-2*cos(2*y)-x-y
grad=f.diff()
show(grad)

1b. Plot the 2-dimensional vector field defined by the gradient of $f$ in the rectangle $(-2,-2) \leq (x,y) \leq (2,2)$.

In [43]:
#source: http://doc.sagemath.org/html/en/reference/plotting/sage/plot/plot_field.html
plot_vector_field((3*cos(x)-1,4*sin(2*y)-1), (x,-2,2), (y,-2,2))

### Problem 2: 3D plotting

Grading criterion: correctness of code.

2a. Draw a 3D plot of a torus.

In [44]:
#Source: http://doc.sagemath.org/html/en/reference/plot3d/sage/plot/plot3d/shapes.html
from sage.plot.plot3d.shapes import *
Torus().show()

2b. Draw a single 3D plot containing the five regular polytopes in it: tetrahedron, cube, octahedron, dodecahedron, icosahedron.  All five must be visible.

In [46]:
#source: http://doc.sagemath.org/html/en/reference/plot3d/sage/plot/plot3d/platonic.html
S = tetrahedron((0,-3.5,0)) + cube((0,-2,0)) + octahedron() + dodecahedron((0,2,0)) + icosahedron(center=(0,4,0))
S.show(aspect_ratio=[1,1,1])

2c. Draw a 3D plot of the [Mexican hat function](https://en.wikipedia.org/wiki/Mexican_hat_wavelet). Try to choose the parameter $\sigma$ to get an authentic "sombrero" look.

In [47]:
sigma=.6
phi(x,y)=1/(pi*sigma**2)*(1-1/2*((x**2+y**2)/sigma**2))*e**(-(x**2+y**2)/(2*sigma**2))
#show(phi)
plot3d(phi,(x,-2,2),(y,-2,2))

### Problem 3: MATLAB (and Octave) vs. Sage

Grading criterion: correctness of code.

This exercise refers to the [Math 18 MATLAB exercise set](http://www.math.ucsd.edu/~math18/).

3a. Do MATLAB exercise 4.5 twice: once using Octave, and a second time using Sage. (For this problem, you will need to switch the kernel between Octave and SageMath.)

In [1]:
%Octave
%part a
P = [0.8100 0.0800 0.1600 0.1000;
0.0900 0.8400 0.0500 0.0800;
0.0600 0.0400 0.7400 0.0400;
0.0400 0.0400 0.0500 0.7800];
[Q,D]=eig(P)
Q*D*inv(Q)
%part b
L=[1 0 0 0; 0 0 0 0; 0 0 0 0; 0 0 0 0];
%part c
Pinf=Q*L*inv(Q)
%part d
x0 = [0.5106; 0.4720; 0.0075; 0.0099];
Pinf*x0
%part e
y=[1/2;1/4;1/8;1/8];
Pinf*y
%there is no difference

Q =


   0.665624   0.767579   0.543214  -0.464102


   0.616521  -0.284124  -0.814822  -0.125380


   0.294620  -0.568248   0.181071  -0.250760


   0.300076   0.084793   0.090536   0.840243


D =


Diagonal Matrix


   1.00000         0         0         0


         0   0.67298         0         0


         0         0   0.76000         0


         0         0         0   0.73702


ans =


   0.810000   0.080000   0.160000   0.100000


   0.090000   0.840000   0.050000   0.080000


   0.060000   0.040000   0.740000   0.040000


   0.040000   0.040000   0.050000   0.780000


Pinf =


   0.35465   0.35465   0.35465   0.35465


   0.32849   0.32849   0.32849   0.32849


   0.15698   0.15698   0.15698   0.15698


   0.15988   0.15988   0.15988   0.15988


ans =


   0.35465


   0.32849


   0.15698


   0.15988


ans =


   0.35465


   0.32849


   0.15698


   0.15988


In [1]:
#SageMath
#part a
print('part a')
P = Matrix(CDF,[[0.8100,0.0800,0.1600,0.1000],[0.0900,0.8400,0.0500,0.0800],[0.0600,0.0400,0.7400,0.0400],[0.0400,0.0400,0.0500,0.7800]])
D,Q = P.eigenmatrix_right()
print(D)
print(Q*D*(~Q)) #returns P
#part b
L=Matrix([[1,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]])
#part c
print('part c')
Pinf=Q*L*(~Q)
print(Pinf)
#part d
print('part d')
x0 = Matrix([[0.5106],[0.4720],[0.0075],[0.0099]])
print(Pinf*x0)
#part e
print('part e')
y=Matrix([[1/2],[1/4],[1/8],[1/8]])
print(Pinf*y)
#there is no difference

part a
[1.0000000000000004                0.0                0.0                0.0]
[               0.0 0.6729843788128368                0.0                0.0]
[               0.0                0.0 0.7599999999999995                0.0]
[               0.0                0.0                0.0 0.7370156211871641]
[  0.8100000000000003  0.08000000000000017  0.15999999999999967  0.10000000000000017]
[ 0.09000000000000037   0.8400000000000001  0.05000000000000002  0.08000000000000021]
[0.059999999999999505 0.040000000000000105   0.7400000000000007 0.040000000000000084]
[ 0.04000000000000018 0.040000000000000153 0.050000000000000114                 0.78]
part c
[  0.354651162790697  0.3546511627906978  0.3546511627906968 0.35465116279069725]
[ 0.3284883720930234  0.3284883720930241 0.32848837209302323  0.3284883720930236]
[0.15697674418604607  0.1569767441860464 0.15697674418604599 0.15697674418604618]
[0.15988372093023273 0.15988372093023306 0.15988372093023265 0.15988372093023284]
pa

3b. Repeat with MATLAB exercise 5.6, using `numpy` to obtain the analogue of MATLAB's least squares functionality.

In [2]:
%Matlab
B=[1 75; 1 100; 1 128; 1 159; 1 195]; d=[15 23 26 34 38]';
%Part a
[Q, R] = qr(B,0)
x = Q(:, 1);
y = Q(:, 2);
v = dot(x,d)*x + dot(y,d)*y
%part b
c=B\v
%B*c-v %checking c is the correction solution
%part c
[cl,stdx,mse] = lscov(B, d, eye(5)); cl

Q =


  -0.447214  -0.594998


  -0.447214  -0.331258


  -0.447214  -0.035869


  -0.447214   0.291169


  -0.447214   0.670955


R =


    -2.23607  -293.81933


     0.00000    94.79029


v =


   16.538


   21.264


   26.557


   32.418


   39.223


c =


   2.35959


   0.18904


cl =


   2.35959


   0.18904


In [2]:
#Sage
B=Matrix(CDF,[[1,75],[1,100],[1,128],[1,159],[1,195]]); d=vector(RR,[15,23,26,34,38])
#Part a
Q, R = B.QR()
x = Q[:,0]; y = Q[:,1]
x = vector(x); y = vector(y); 
v = x.dot_product(d)*x + y.dot_product(d)*y
print('v=',v)
#part b
#from the octave part, we know that Bc=v has a solution, therefore we can reduce the matrix B from 5x2 to 2x2
Bsub=B[0:2,:]; vsub=v[0:2]
Bsub=Bsub.change_ring(RR);vsub=vsub.change_ring(RR) 
c = Bsub.solve_right(vsub)
print('c=',c)
#print(B*c-v) #checking c is the correction solution
#part c
import numpy as np
print(np.linalg.lstsq(np.array(B),np.array(d))[0])

('v=', (16.53790678003827, 21.264011930730526, 26.55724969950585, 32.41762008636424, 39.223211503361085))
('c=', (2.35959132790000, 0.189044206028000))
[ 2.35959133+0.j  0.18904421+0.j]


### Problem 4: Eigenvectors and eigenvalues

Grading criteria: correctness of code and explanations.

Let $M$ be the following matrix with rational entries:
$$
M = \left(\begin{array}{rrrr}
\frac{1}{2} & 0 & -1 & 0 \\
1 & \frac{1}{2} & 1 & 1 \\
0 & 1 & -1 & -1 \\
2 & 1 & -2 & 1
\end{array}\right)
$$

4a. State the Cayley-Hamilton theorem, then use Sage to verify that it holds for $M$.

In [3]:
#Cayley-Hamilton theorem says that plugging in M into the characteristic polynomial yields the 0 matrix
M=Matrix([[1/2,0,-1,0],[1,1/2,1,1],[0,1,-1,-1],[2,1,-2,1]])
poly=M.charpoly()
show(poly)
poly(M)

[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]

4b. Compute the eigenvalues and eigenvectors of $M$, and verify (using numerical approximations) that each eigenvector is indeed an eigenvector with the specified eigenvalue.

In [4]:
#source: http://doc.sagemath.org/html/en/constructions/linear_algebra.html#eigenvectors-and-eigenvalues
#print(M.eigenvalues())
eigvects=M.eigenvectors_right()
print(eigvects)

#verifying eigenvectors
print('--------------------------------------------------------------------------------------------------------------')
eigvect1=vector((1, -3, -1/2, -2))
lambda1=1
print(M*eigvect1,lambda1*eigvect1)
print('--------------------------------------------------------------------------------------------------------------')

eigvect2=vector((1, -1.958489365417388, 2.800719103558421, 1.684459476282067))
lambda2=-2.300719103558421
print(M*eigvect2,lambda2*eigvect2)
print('--------------------------------------------------------------------------------------------------------------')

eigvect3=vector((1, -0.7606864653899139, 0.2328271243493423, -1.055718682081144))
lambda3=0.2671728756506578
print(M*eigvect3,lambda3*eigvect3)
print('--------------------------------------------------------------------------------------------------------------')

eigvect4=vector((1, 7.719175830807302, -1.533546227907764, 12.37125920579908))
lambda4=2.033546227907764
print(M*eigvect4,lambda4*eigvect4)

[(1, [
(1, -3, -1/2, -2)
], 1), (-2.300719103558421?, [(1, -1.958489365417388?, 2.800719103558421?, 1.684459476282067?)], 1), (0.2671728756506578?, [(1, -0.7606864653899139?, 0.2328271243493423?, -1.055718682081144?)], 1), (2.033546227907764?, [(1, 7.719175830807302?, -1.533546227907764?, 12.37125920579908?)], 1)]
--------------------------------------------------------------------------------------------------------------
((1, -3, -1/2, -2), (1, -3, -1/2, -2))
--------------------------------------------------------------------------------------------------------------
((-2.30071910355842, 4.50593389713179, -6.44366794525788, -3.87546809625216), (-2.30071910355842, 4.50593389713179, -6.44366794525787, -3.87546809625216))
--------------------------------------------------------------------------------------------------------------
((0.267172875650658, -0.203234790426759, 0.0622050923418879, -0.282059396169743), (0.267172875650658, -0.203234790426758, 0.0622050923418871, -0.282059396169

4c. State the relationship between the characteristic polynomial, the determinant, and the eigenvalues of a matrix; then verify numerically that this holds for $M$.

The characteristic polynomial is the polynomial where the eigenvalues are the roots and the determinant is the product of the eigenvalues.

In [5]:
#verifying that the eigenvalues are the roots of the characteristic polynomial
print(poly(lambda1),poly(lambda2),poly(lambda3),poly(lambda4));
#verifying that the product of the eigenvalues is the determinant
print(lambda1*lambda2*lambda3*lambda4,det(M))

(0, -7.43849426498855e-15, 3.33066907387547e-16, 5.99520433297585e-15)
(-1.25000000000000, -5/4)


### Problem 5: Hilbert matrices and numerical stability

Grading criterion: correctness of code and thoroughness of explanation.

5a. Define a Python function `f`, which on the input of a positive integer $n$, returns the $n \times n$ Sage matrix over the rational numbers 
$$
H_{ij} = \frac{1}{i+j-1} \qquad (i,j=1,\dots,n).
$$
See below for a sample output.
Hint: remember that Sage, like Python, starts indexing with 0 instead of 1.

In [1]:
def f(n):
    #initalize the matrix entries
    v=range(n**2)
    #fills the entries using the formula
    index=0
    for i in range(1,n+1):
        for j in range(1,n+1):
            v[index]=1/(i+j-1)
            index=index+1
    #formats the entries into an nxn matrix
    return Matrix(n,n,v)

In [2]:
f(3)

[  1 1/2 1/3]
[1/2 1/3 1/4]
[1/3 1/4 1/5]

5b. Write Sage code to compute the inverse of `f(25)`, print out the top left entry (not the whole matrix), and verify that the whole answer agrees with the [formula in Wikipedia](https://en.wikipedia.org/wiki/Hilbert_matrix).

In [8]:
X=f(25)
#~ is inverse in sage
Y=~X

#creating the theoretical inverse matrix using the wikipedia formula
inverse = matrix.identity(25)
n=25
for i in range(25):
    i = i+1
    for j in range(25):
        j = j+1
        inverse[i-1,j-1] = (-1)**(i+j)*(i+j-1)*binomial(n+i-1,n-j)*binomial(n+j-1,n-i)*binomial(i+j-2,i-1)**2

#comparisons
print(inverse[0,0] == Y[0,0])
print(Y[0,0])
print(inverse == Y)i=1;j=1

True
625
True


5c. Use the `change_ring` method to redo the computation of the inverse of `f(25)` over the ring `RR` (i.e., using floating-point real numbers with double precision == 53 bits), agian printing out the top left entry.

In [9]:
Z=X.change_ring(RR)
W=~Z
print(W[0][0])

-202.301237192348


5d. In as much detail as you can, explain what you have just observed. You may want to compute the determinant of `f(25)` and/or read about [numerical stability](https://en.wikipedia.org/wiki/Numerical_stability).

In [10]:
print(det(X),det(Z))
#Because Z and W are over the ring RR, there is some round-off and truncated errors. However these round-off errors in the inital matrix, caused by small eigenvalues or eigenvalues that nearly cancel each other out, lead to large deviations in the final answer. What we witnessed is small errors being magnified such that the approximated solution deivated very far from the exact solution.

(1/746332515470541859307349018107431789872329747913727730760621191984777569063589205517303938509441565299809996599554994981363939681729476785432795097905555120762172958990784084457536372476333251919350316666089029356479086324949498677522696089012012028938712165715166669721997554754957779660912439584392373862400000000000000000000000000000000000000000000000000, 2.91038304567337e-11)


### Problem 6: Linear algebra over Q

Grading criteria: correctness of code and thoroughness of explanation.

6a. Explain in detail what the following code does and how it is being done. Assume that the input `M` is a matrix with entries in `QQ`.

In [1]:
def f(M):
    M = copy(M) # replace M with a copy to avoid clobbering the original
    n = M.dimensions()[0]
    if n != M.dimensions()[1]: raise ValueError
    for i in range(n):
        j = i
        while j<n and M[j,i] == 0: j += 1
        if j==n: return(0)
        if i<j:
            M.swap_rows(i,j)
            M.rescale_row(i, -1)
        for k in range(i+1,n):
            M.add_multiple_of_row(k,i,-M[k,i]/M[i,i])
    return(prod(M[i,i] for i in range(n)))

Overview: The function f row reduces the matrix M into a triangular matrix then takes the product of the diagonal entries which yields the determinant of M. 

First the fucntion makes a copy of M to work with locally. Then the function checks to see if M is a square matrix, if not the function will spit back an error. Then for each column of M, indexed by i, it swaps the rows starting with zeroes and the rows starting without zeroes- resulting in the nonzero rows at the top and rows starting with zero at the bottom and scaling appropriately. Then it procedes to row reduce by adding a scalar multiple of the ith row to all the other rows below it. This algorithm transforms a general matrix M into an upper triangular matrix which has the nice property that the product of the diagonal entries is the determiant- which is what is ebign returned.

6b. Define a Python function `g` that, on input a positive integer `n`, returns an $n \times n$ matrix in which each entry is a Sage integer is chosen uniformly at random among 0 and 1. (Hint: use the `randint` function, but read the docstring carefully!) 

Then check that on the output of `g(25)`, the function `f` agrees with the native Sage way of doing the same computation.

In [2]:
def g(n):
    # your code goes here
    #initalize the matrix entries
    p=range(n**2)
    #fills the entries with sage integer 0 or 1 chosen uniformly at random
    for i in range(n**2):
        p[i]=Integer(randint(0,1))
    #formats the entries into an nxn matrix
    return Matrix(n,n,p)

In [3]:
mat=g(25).change_ring(QQ)
#show(mat)
#type(mat[0][0])
print(det(mat))
print(f(mat))

66108
66108


6c. Define the *binary height* of a nonzero rational number $\frac{r}{s}$, written in lowest terms, to be the quantity
$$ \left\lceil\log_2 r \right\rceil + \left\lceil \log_2 s \right\rceil.$$
Use the function `binary_height` defined below to compute this.

Take the code defining `f`, recopy it below, then modify it so that at the last step, instead of returning the product of the diagonal entries of `M`, it returns the maximum of the heights of the diagonal entries.

In [4]:
def binary_height(x):
    return(x.numer().nbits() + x.denom().nbits())

In [5]:
def f_modified(M):
    M = copy(M) # replace M with a copy to avoid clobbering the original
    n = M.dimensions()[0]
    if n != M.dimensions()[1]: raise ValueError
    for i in range(n):
        j = i
        while j<n and M[j,i] == 0: j += 1
        if j==n: return(0)
        if i<j:
            M.swap_rows(i,j)
            M.rescale_row(i, -1)
        for k in range(i+1,n):
            M.add_multiple_of_row(k,i,-M[k,i]/M[i,i])
    return(max(binary_height(M[i,i]) for i in range(n)))

6d. Explain, in words, the output of the following code. (It should run without errors!)

In [10]:
M = g(25).change_ring(QQ)
print(binary_height(f(M)))
print(f_modified(M))

17
31


The first print statement is the binary height of the determiant of M. The second print statement is finding the maximum binary height of the diagonal entries of a row reduced M. The answer is different because the first returns the binary height of the determiant, whereas the second returns one binary height- the maximum of the binary heights of the diagonal entries of a row reduced M. The magnitude of both answers are the same, even if the actual values are different due to randomness. 

6e. Sage does *not* use the method illustrated by the definition of `f` for matrices of integers or rational numbers; instead, it uses an approach based on the [Chinese remainder theorem](https://en.wikipedia.org/wiki/Chinese_remainder_theorem), in which one does the analogous computation modulo $p$ for a few primes $p$. Explain why you think this decision was made.

I think this decision was made because it allows Sage to deal with very large numbers very efficiently. If a matrix of size 1000000x1000000 were passed into f, the algorithm would have to make at least $1000000^2$ iterations from the loops alone. The approach based on the Chinese remainder theorem allows for quicker computation due to the use of modular arithematic and equivalence.